### ISSUE TITLE
Memory leak + App crash

### ISSUE THREAD

**Issue by AKprisonER** [blakelee/CoinProfits#2]
Well it happened on emulator and real device too

**Comment by blakelee** [comment]
I fixed the app crash. Not sure about the memory leak. I've seen the leak app pop up a few times but it hasn't actually reported any leaks for me.

**Comment by AKprisonER** [comment]
i think its due to storage permissions it seems

**Comment by AKprisonER** [comment]
![capture](https://user-images.githubusercontent.com/4397720/31981888-7d8ed1a2-b973-11e7-8101-cdc2aab53b2f.PNG)
using canaryleak...it dosent show any leaks in its screen.
Its just keeps showing and memory dump occuring
![hgf](https://user-images.githubusercontent.com/4397720/31981879-72bfa896-b973-11e7-895a-fa63ca8a9574.PNG)

**Comment by blakelee** [comment]
Did the new commit fix the crashes for you? Rc1 of lifecycle components broke support with rxlifecycle so rxlifecycle needs to be updated.

That's what's been happening with me. No leaks yet it still pops up. I think it's due to rxlifecycle.

**Comment by AKprisonER** [comment]
Memory leak is happening due to FinalizerReference it seems
1. Coinprofits.model
2.Coinprofits,fragment

 And finally,i came to a conclusion that kotlin is still not perfect for android apps

**Comment by blakelee** [comment]
Stack overflow seems to not have a lot of information about it. Since you said it's in a fragment I have an idea where to look. 

The overview fragment doesn't have any separation. I need to restructure it to mvvm. Once it has some better architecture, maybe the issue will solve itself.

I'm pretty happy with using kotlin so far. Just takes a bit to get used to

**Comment by AKprisonER** [comment]
How to add multi currency ?
As i am out of USD, like choose display currency from Euro or Krw or Inr

**Comment by blakelee** [comment]
I setup the db so that eventually I could add differing currencies. Coinmarketcap has api calls for different ones. However, the map api only allowed for usd. I'm not sure how I wanted to implement it. I was thinking of having usd be the base and having a multiplier for the other currencies

**Comment by AKprisonER** [comment]
Any implementation of other currencies
